ROOT=..
#PLATFORM=$(shell $(ROOT)/systype.sh)
include $(ROOT)/Make.defines

PROGS =	6-1 

all:	$(PROGS)

%:	%.c $(LIBAPUE)
	$(CC) $(CFLAGS) $@.c -o $@ $(LDFLAGS) $(LDLIBS)

clean:
	rm -f $(PROGS) $(TEMPFILES) *.o

include $(ROOT)/Make.libapue.inc
